### ISSUE TITLE
UML diagram of babyagi.py

### ISSUE THREAD

**Issue by QasimWani** [yoheinakajima/babyagi#102]
hey! I used [Graphical Code Tracer](https://github.com/QasimWani/gct) to create a UML diagram of [babyagi.py](https://github.com/yoheinakajima/babyagi/blob/main/babyagi.py) to help beginners understand your code. Would love it if you could attach it to the readme. Have better context now with this visualization 😄 

<img width="1280" alt="image" src="https://user-images.githubusercontent.com/43754306/230748015-1747c5f2-3c28-4d03-910f-cac34f798291.png">

**Comment by abhiprojectz** [comment]
@QasimWani  Can you do the same for singularGPT ??
