### ISSUE TITLE
task repetition, sparse output

### ISSUE THREAD

**Issue by stutteringp0et** [yoheinakajima/babyagi#104]
I left it running a content mapping research task, and it ran the same tasks over-and-over, 37 times (yes, I counted)

I'm left with the suspicious feeling that this is designed to do nothing but eat up OpenAI tokens.

In 8 hours, the content map it came up with is 19 items long.  This is less than I get with a single (shorter) prompt in the playground or chat.

It's definitely creating the pinecone storage area, but for some reason it can't seem to remember anything (37 repeats).

**Comment by Kheurt** [comment]
Got the same issue... but I did not find how to solve it
