### ISSUE TITLE
Pinecone has no attribute 'init'

### ISSUE THREAD

**Issue by walrusthief** [yoheinakajima/babyagi#106]
Hi there! Tried to solve this one myself but I'm stumped. Every time I run babyagi.py I get this message. I've got the API keys and environment name verified and in my .env file. Any ideas?

Traceback (most recent call last):
  File "C:\Users\darko\Downloads\babyagi-main\babyagi-main\babyagi.py", line 81, in <module>
    pinecone.init(api_key=PINECONE_API_KEY, environment=PINECONE_ENVIRONMENT)
AttributeError: module 'pinecone' has no attribute 'init'

**Comment by walrusthief** [comment]
Uninstalled and reinstalled pinecone-client, and it at least bumped me to a different error... involving Pinecone's API being invalid that I'm sure I've checked over 20 times.

**Comment by Guiyom974** [comment]
Hi,
Unfortunately I still receive the same error: AttributeError: module 'pinecone' has no attribute 'init'
I've re-installed pinecone a few times already but it didn't work. Any clue how to solve it?

**Comment by dohaibac** [comment]
This error come because you named your file is pinecone.py
Please rename your file and this will be gone.

**Comment by Bismarck1936** [comment]
> Uninstalled and reinstalled pinecone-client, and it at least bumped me to a different error... involving Pinecone's API being invalid that I'm sure I've checked over 20 times.

How did you solve the issue?

**Comment by CoribTut** [comment]
try to pip3 install "pinecone-client[grpc]"

**Comment by hamsho93** [comment]
Hey i seem to be having the same issue 
"AttributeError: module 'pinecone' has no attribute 'init'" 

I created a new kernel in my notebook to try and fix but no luck. Any advice on how to solve the issue?

**Comment by victaphu** [comment]
Hi all, 
I had the same problem and it looks like the library changed. Check out:
https://pypi.org/project/pinecone-client/

This worked for me:
```
from pinecone import Pinecone
pc = Pinecone(api_key=api_key)
index = pc.Index(host='<host>')

```
Hope this helps someone out there, was a real head scratcher for me
