### ISSUE TITLE
Is result needed in Pinecone metadata?

### ISSUE THREAD

**Issue by pj4533** [yoheinakajima/babyagi#109]
I have ported BabyAGI to swift, and had a question about how context is used. (So this is more a discussion point, not an issue)

It seems that the context in the execution agent is a list of the previously completed tasks, by name, not including the results? (Unless my python read is bad, which could be the case!) I guess I understand that the execution doesn't need the previous results, just what was completed (ie the task names). And the result is what is used to create the embedding vector. 

But if that's true, is there any reason to also store the whole result in Pinecones metadata?

**Comment by francip** [comment]
It's good to store the results in the Pinecone so people can look at what was done (tools/results_broswer.py). But you also bring a good point - seems the results of the tas execution should be part of the context, not just the task itself. We currently do not have a way to distinguish a task that logically failed ("I will call to confirm the reservation" -> "I was not able to call") from success ("I will call to confirm the reservation" -> "Reservation was confirmed"), and the context only knows that an attempt was made to call, so next task execution assumes success.

**Comment by francip** [comment]
Dang it, adding the results to the context drastically improved the processing.

![image](https://user-images.githubusercontent.com/49422/230757871-b50878b8-532b-4367-b006-8bbc30c2bfe7.png)

**Comment by pj4533** [comment]
I was wondering if that might be the case, but I'm pretty new to all this, so figured it wasn't necessary! I'll try adding the results to context in my swift code also.

Thanks for the help!
