### ISSUE TITLE
How do you delete current objective and start over?

### ISSUE THREAD

**Issue by stclair-github** [yoheinakajima/babyagi#119]
How do you delete current objective and start over?  Anyone?  Bueller?

**Comment by HornHighYo** [comment]
You can either update your .env file or add a line of python code like:  OBJECTIVE = 'your new objective'  prior to the PINECONE_API_KEY = os.getenv("PINECONE_API_KEY", "")

**Comment by stclair-github** [comment]
Ahh yes! Thank you.

I was drinking wine and working with one eye. Forgot I put those there. 👍🏼
