### ISSUE TITLE
Is it possible to run without an OpenAi API key

### ISSUE THREAD

**Issue by SumDevv** [yoheinakajima/babyagi#124]
I'm wondering if there's alternative to the OpenAI API, such as a self-hosted model that can do the same?

**Comment by Jawad1347** [comment]
> I'm wondering if there's alternative to the OpenAI API, such as a self-hosted model that can do the same?

Good question, I was about to ask the same. Vicuna should be fine replacement, but how.

**Comment by HornHighYo** [comment]
Imagine there is a way to use the huggingface api

**Comment by alexdzm** [comment]
Hey, you can use llama. See this from the README:

> Llama
> 
> Download the latest version of [Llama.cpp](https://github.com/ggerganov/llama.cpp) and follow instructions to make it. You will also need the Llama model weights.
> 
> Under no circumstances share IPFS, magnet links, or any other links to model downloads anywhere in this repository, including in issues, discussions or pull requests. They will be immediately deleted.
> After that link llama/main to llama.cpp/main and models to the folder where you have the Llama model weights. Then run the script with OPENAI_API_MODEL=llama or -l argument.

**Comment by alexdzm** [comment]
See also #130 for some helpful tips on getting this to work!

**Comment by francip** [comment]
Theoretically, you can run BabyAGI with any models supported by llama.cpp. We haven't done extensive testing, and it's possible the prompts need to be changed, but the infra to enable this is there.
