### ISSUE TITLE
llama confusion

### ISSUE THREAD

**Issue by iplayfast** [yoheinakajima/babyagi#130]
Can the readme be updated to explain how to interface with llama? I've tried
./babyagi.py -l llama -m models/ggml-vicuna-13b-4bit.bin 
Setting the .env 
OPENAI_API_KEY=
OPENAI_API_MODEL=llama

As far as I know there is no OPENAI_API_KEY as it is run locally on my computer.

**Comment by MikoAL** [comment]
do 
mklink "llama/main"  C:\Users\User\Desktop\Projects\llama\llama.cpp\build\bin\Release\main.exe
in the cmd

remember to create the folder "llama" and copy the file "main.exe" into it.

NOTE: I am a confused idiot and this may be a completely wrong interpretation of what to do, as I have been running into problems with the OPENAI_API_KEY as well

**Comment by ai8hyf** [comment]
What I did was changing this line `cmd = cmd = ["llama/main", "-p", prompt]` to pointing to my llama model.
However, to fully run locally, you also need a embedding model like SBert bacause the default embedding model is OpenAI's ada model (cheap but still costs money).
I haven't been able to run things fully locally, but I think I am very close.

**Comment by Tobias-GH-Schulz** [comment]
@ai8hyf it would be great if you could share how you made run fully locally as soon as you get it done :) thx

**Comment by maxencry** [comment]
> What I did was changing this line `cmd = cmd = ["llama/main", "-p", prompt]` to pointing to my llama model. However, to fully run locally, you also need a embedding model like SBert bacause the default embedding model is OpenAI's ada model (cheap but still costs money). I haven't been able to run things fully locally, but I think I am very close.

I've already tried error: 

raise ApiValueError('Unable to prepare type {} for serialization'.format(obj.__class__.__name__))
pinecone.core.client.exceptions.ApiValueError: Unable to prepare type ndarray for serialization

**Comment by ai8hyf** [comment]
> @ai8hyf it would be great if you could share how you made run fully locally as soon as you get it done :) thx

Just check this out: https://python.langchain.com/en/latest/use_cases/agents/baby_agi.html
I think it solves all the problems here.

**Comment by ai8hyf** [comment]
> > What I did was changing this line `cmd = cmd = ["llama/main", "-p", prompt]` to pointing to my llama model. However, to fully run locally, you also need a embedding model like SBert bacause the default embedding model is OpenAI's ada model (cheap but still costs money). I haven't been able to run things fully locally, but I think I am very close.
> 
> I've already tried error:
> 
> raise ApiValueError('Unable to prepare type {} for serialization'.format(obj.**class**.**name**)) pinecone.core.client.exceptions.ApiValueError: Unable to prepare type ndarray for serialization

Check this implementation using LangChain: https://python.langchain.com/en/latest/use_cases/agents/baby_agi.html

**Comment by ai8hyf** [comment]
> > > @ai8hyf it would be great if you could share how you made run fully locally as soon as you get it done :) thx
> > 
> > 
> > Just check this out: https://python.langchain.com/en/latest/use_cases/agents/baby_agi.html I think it solves all the problems here.
> 
> Creates more problems because it is still needs the openai api and does not explain to how use local llama models instead.

I put together a very rough solution for langchain+llama+babyAGI. See my fork here: 
https://github.com/ai8hyf/babyagi/blob/main/langChain-llama.py

**Comment by francip** [comment]
I'd love to get the llama code updated. The initial hack was based on building/running llama.cpp under Linux, so no support for Windows. Also, the embeddings are still based on OpenAI Ada, so OpenAI key is still needed.

But if you have improvements to fix those, I'd love to get a PR to integrate in.

**Comment by ai8hyf** [comment]
> I'd love to get the llama code updated. The initial hack was based on building/running llama.cpp under Linux, so no support for Windows. Also, the embeddings are still based on OpenAI Ada, so OpenAI key is still needed.
> 
> But if you have improvements to fix those, I'd love to get a PR to integrate in.

Sorry I don't have a Windows dev machine right now so I don't really know the situation with Windows. The embeddings are also from local llama cpp model (4096 size). The only 3rd-party API used in my code snippet was the SerpAPIWrapper. I basically used LangChain's official example (https://python.langchain.com/en/latest/use_cases/agents/baby_agi.html) and changed the models and embeddings to llama cpp.

**Comment by dany-on-demand** [comment]
> > > > @ai8hyf it would be great if you could share how you made run fully locally as soon as you get it done :) thx
> > > 
> > > 
> > > Just check this out: https://python.langchain.com/en/latest/use_cases/agents/baby_agi.html I think it solves all the problems here.
> > 
> > 
> > Creates more problems because it is still needs the openai api and does not explain to how use local llama models instead.
> 
> I put together a very rough solution for langchain+llama+babyAGI. See my fork here: https://github.com/ai8hyf/babyagi/blob/main/langChain-llama.py

For whatever reason, I had to set embedding_size = 5120 for your script to work

**Comment by ai8hyf** [comment]
> > > > > @ai8hyf it would be great if you could share how you made run fully locally as soon as you get it done :) thx
> > > > 
> > > > 
> > > > Just check this out: https://python.langchain.com/en/latest/use_cases/agents/baby_agi.html I think it solves all the problems here.
> > > 
> > > 
> > > Creates more problems because it is still needs the openai api and does not explain to how use local llama models instead.
> > 
> > 
> > I put together a very rough solution for langchain+llama+babyAGI. See my fork here: https://github.com/ai8hyf/babyagi/blob/main/langChain-llama.py
> 
> For whatever reason, I had to set embedding_size = 5120 for your script to work

ooof, I think that's because you are using a 13b model? Mine was based on the 7b model.

**Comment by EinGeist** [comment]
> > > > @ai8hyf it would be great if you could share how you made run fully locally as soon as you get it done :) thx
> > > 
> > > 
> > > Just check this out: https://python.langchain.com/en/latest/use_cases/agents/baby_agi.html I think it solves all the problems here.
> > 
> > 
> > Creates more problems because it is still needs the openai api and does not explain to how use local llama models instead.
> 
> I put together a very rough solution for langchain+llama+babyAGI. See my fork here: https://github.com/ai8hyf/babyagi/blob/main/langChain-llama.py
 
First I would love to thank you for this implementation. 

I have tried it but it didn't generate any response at all. 
I'm using gpt4all-lora-quantized-ggml.bin model.

Any idea why is that?
