### ISSUE TITLE
Issues with attempts at utilizing local llama models

### ISSUE THREAD

**Issue by InfernalDread** [yoheinakajima/babyagi#142]
Hello everyone,

Let me start off by saying that I am not an extreme tech savvy person. I had attempted to follow the steps shown on how to use the local llama models in the README, but I would always end up with the error requesting me to supply an OPENAI API. Can someone who is immensely smarter than me provide me with a tutorial (preferably a video tutorial to follow), so that I may correctly test local models?

I also know that there is this link from langchain: https://python.langchain.com/en/latest/use_cases/agents/baby_agi.html

However, I am not sure how to implement this, to get the local models to work.

Thank you all for your time!

**Comment by romilly** [comment]
The code seems to ask for an OpenAI API key even if you use llama.cpp, but I think it will be ignored. Try setting a random string as key.

**Comment by romilly** [comment]
Oops! Looking more carefully at the code, it uses openai to generate embeddings even if you use the llama.cpp code for chat. So you'll need to have an OpenAI account and set an OpenAI key.

**Comment by InfernalDread** [comment]
Oh ok, thanks for the help! Maybe sometime in the future, someone will create a method to use a local embedding!
