### ISSUE TITLE
Use of open source or free alternatives instead of paid APIs

### ISSUE THREAD

**Issue by superchargez** [yoheinakajima/babyagi#145]
Is there a way to use [Open-Assistant](https://open-assistant.io/chat) or [ChatGPT](https://chat.openai.com/chat) or to run LLaMA in google colab?

And free alternative to Pinecone like FAISS running locally or in google colab?

**Comment by wsippel** [comment]
I've heard of a few organisations successfully making the switch from Pinecone to Weaviate, which is free and open source and can even be embedded. Seems ideal for a purely local installation, but I'm not sure if it's suitable for babyagi.

**Comment by RajdeepBorgohain** [comment]
I have been working with Weaviate and have been using in our product. I can help in this issue

**Comment by terbo** [comment]
> I have been working with Weaviate and have been using in our product. I can help in this issue

Can you give any insight on Weaviate vs Chroma? I've been playing with the it hoping it had enough features for simple memory.

**Comment by francip** [comment]
BabyAGI supports local LLAMA, but that does require rather beefy computer. If you want to extend the code to instead call hosted LLAMA instances, that would be great.

As for replacing Pinecone - there are couple of folks (@atroyn and @kyleshrader) working on replacing it with Weaviate or Chroma. They have a draft PR (https://github.com/yoheinakajima/babyagi/pull/141) you can join the conversation at.

**Comment by bobvanluijt** [comment]
> I have been working with Weaviate and have been using in our product. I can help in this issue

This is awesome!

CC: @hsm207 note: https://github.com/yoheinakajima/babyagi/pull/141/files

**Comment by keldenl** [comment]
you can replace chat easily with https://github.com/keldenl/gpt-llama.cpp

embeddings on the other hand.. i wish there was a in-built way for local embeddings and sentence-transformers so we could avoid using openai

**Comment by jakvb** [comment]
#208 here it is implemented and working with vicuna

**Comment by CRCODE22** [comment]
`> #208 here it is implemented and working with vicuna

I tried it does load the vicuna model but still it requires a working openai api key.

(babyagi) D:\babyagi>python babyagi.py --Llama
llama.cpp: loading model from D:/babyagi/models/ggml-vicuna-7b-1.1-q4_1.bin
llama_model_load_internal: format     = ggjt v1 (latest)
llama_model_load_internal: n_vocab    = 32000
llama_model_load_internal: n_ctx      = 2048
llama_model_load_internal: n_embd     = 4096
llama_model_load_internal: n_mult     = 256
llama_model_load_internal: n_head     = 32
llama_model_load_internal: n_layer    = 32
llama_model_load_internal: n_rot      = 128
llama_model_load_internal: ftype      = 3 (mostly Q4_1)
llama_model_load_internal: n_ff       = 11008
llama_model_load_internal: n_parts    = 1
llama_model_load_internal: model size = 7B
llama_model_load_internal: ggml ctx size =  59.11 KB
llama_model_load_internal: mem required  = 6612.57 MB (+ 1026.00 MB per state)
....................................................................................................
llama_init_from_file: kv self size  = 1024.00 MB
AVX = 1 | AVX2 = 1 | AVX512 = 0 | AVX512_VBMI = 0 | AVX512_VNNI = 0 | FMA = 1 | NEON = 0 | ARM_FMA = 0 | F16C = 1 | FP16_VA = 0 | WASM_SIMD = 0 | BLAS = 0 | SSE3 = 1 | VSX = 0 |

*****OBJECTIVE*****

Solve world hunger

Initial task: Develop a task list

*****TASK LIST*****

1: Develop a task list

*****NEXT TASK*****

1: Develop a task list
Traceback (most recent call last):
  File "D:\babyagi\babyagi.py", line 289, in <module>
    result = execution_agent(OBJECTIVE, task["task_name"])
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\babyagi\babyagi.py", line 240, in execution_agent
    context = context_agent(query=objective, top_results_num=5)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\babyagi\babyagi.py", line 262, in context_agent
    query_embedding = get_ada_embedding(query)
                      ^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\babyagi\babyagi.py", line 141, in get_ada_embedding
    return openai.Embedding.create(input=[text], model="text-embedding-ada-002")[
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\anaconda3\envs\babyagi\Lib\site-packages\openai\api_resources\embedding.py", line 33, in create
    response = super().create(*args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\anaconda3\envs\babyagi\Lib\site-packages\openai\api_resources\abstract\engine_api_resource.py", line 153, in create
    response, _, api_key = requestor.request(
                           ^^^^^^^^^^^^^^^^^^
  File "E:\anaconda3\envs\babyagi\Lib\site-packages\openai\api_requestor.py", line 226, in request
    resp, got_stream = self._interpret_response(result, stream)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\anaconda3\envs\babyagi\Lib\site-packages\openai\api_requestor.py", line 620, in _interpret_response
    self._interpret_response_line(
  File "E:\anaconda3\envs\babyagi\Lib\site-packages\openai\api_requestor.py", line 683, in _interpret_response_line
    raise self.handle_error_response(
openai.error.RateLimitError: You exceeded your current quota, please check your plan and billing details.
`
