### ISSUE TITLE
How to get out put of end results?

### ISSUE THREAD

**Issue by A1Marky** [yoheinakajima/babyagi#146]
I wasn't sure where to post about this but I've been running BabyAGI a good amount of time now but where would I see any kind of output on the results. It seems like it's doing a ton of stuff but how do I get the output?

**Comment by antoniocascais** [comment]
I only used BabyAGI for like 5min, but one way is to redirect the output to a file:
```
python babyagi.py > output
```

This way the script will not print anything to the console and will instead print all the information to a file named `output`. Important: it will only print to file once you stop the script, so you won't see any information until you stop it.

There's probably a smarter way to achieve this, though.

**Comment by A1Marky** [comment]
> I only used BabyAGI for like 5min, but one way is to redirect the output to a file:
> 
> ```
> python babyagi.py > output
> ```
> 
> This way the script will not print anything to the console and will instead print all the information to a file named `output`. Important: it might take some time to print the output to the file, so don't worry if you see the file empty while the script is running. Give it some time (or stop the script)
> 
> There's probably a smarter way to achieve this, though.

Ok I will give it a try. Thanks. I ran it for like 2 hours last night and didn't get an output of any kind so that hurt. Hopefully I can figure it out for the next try.

**Comment by stepsal** [comment]
I use this on linux.
`python babyagi.py 2>&1 | tee output.txt >/dev/tty`

**Comment by roubkar** [comment]
With this integration you'll be able to explore all outputs with a nice UI: https://github.com/yoheinakajima/babyagi/issues/158
