### ISSUE TITLE
Modular Abilities

### ISSUE THREAD

**Issue by henryruss2** [yoheinakajima/babyagi#152]
Summary 💡
There is a folder called "abilities" that has modular folders for abilities the AI can perform. Inside the folder are python files that can do anything. The AI can call it by outputting "run [FILE_NAME]".

Examples 🌈
I make an ability for the AI to tweet using the Twitter API.
I tell it to get as many followers on Twitter as possible.
It can actually post things on twitter because of this.

Motivation 🔦
AGI

**Comment by estiens** [comment]
Langchain integration will be able to cover most of these use cases
