### ISSUE TITLE
Enable metadata tracking with Aim

### ISSUE THREAD

**Issue by roubkar** [yoheinakajima/babyagi#158]
Hey, Ruben from [Aim](https://github.com/aimhubio/aim) here! 👋

First of all thanks for this awesome project!

After experimenting with babyagi I found that integrating Aim can be extremely helpful for prompts exploration and comparison.

How can Aim enhance babyagi observability?
---

**Prompts comparison**

Here is an example view where it is possible to explore and compare the outputs for the same objective by different models (`gpt-3.5-turbo` and `text-davinci-003`):

<img width="1680" alt="Screen Shot 2023-04-13 at 22 24 02" src="https://user-images.githubusercontent.com/9951653/231850040-648080ce-a648-406c-b0db-374f13c6f8a0.png">

**Generated tokens count comparison**

The same example for generated tokens count:

<img width="1680" alt="Screen Shot 2023-04-13 at 22 27 46" src="https://user-images.githubusercontent.com/9951653/231850812-ee6090ec-9291-4c25-81df-3334f294a410.png">

**Log messages for debugging**

<img width="1678" alt="Screen Shot 2023-04-13 at 22 32 26" src="https://user-images.githubusercontent.com/9951653/231851713-03b3f3b4-02ea-42a7-8b8b-cc24cc0c815d.png">

**View the entire session terminal logs**

<img width="1680" alt="Screen Shot 2023-04-13 at 22 33 56" src="https://user-images.githubusercontent.com/9951653/231852010-eb2074c5-fbf1-4b70-820d-69f29804b26f.png">

**Comment by roubkar** [comment]
Hey @yoheinakajima and @francip, any thoughts on this?
Would like to hear your feedback on this 🙏

**Comment by letsgoduke** [comment]
would like to see this as well
