### ISSUE TITLE
Remove russian flag

### ISSUE THREAD

**Issue by su77ungr** [yoheinakajima/babyagi#159]

**Comment by sb0ddy** [comment]
Y?

**Comment by awwar** [comment]
Dude, the flag is a link to the documentation in Russian. Look in PR section - there are a lot of requests for adding other translations. Support them or add another, then there will be more flags.

**Comment by francip** [comment]
As others said, Russian flag is just a link to a Russian translation of the README.md. Also, it's just one of many translations added.
