### ISSUE TITLE
Stop code and give human feedback

### ISSUE THREAD

**Issue by juanfradb** [yoheinakajima/babyagi#161]
It will be great if with a command or keyboard I can stop babyagi and provide some feedback

**Comment by jarodchang-sudo** [comment]
yah. And it just keeps running and runnning. Where does it end and how does it summarize all the findings up?

**Comment by DonTido** [comment]
Hello, New here. Not sure of the proper etiquette. I added the following code to the babyagi.py code and it seemed to work for me. Hope this is helpful.

`# Add user interactions to the task list
def user_interaction():
    while True:
        print("\033[96m\033[1m" + "\n*****USER INPUT*****\n" + "\033[0m\033[0m")
        print("Select an option:")
        print("1. Modify tasks")
        print("2. Proceed")
        print("3. Stop and exit")
        user_input = input("Enter the number corresponding to your choice: ")

        if user_input == "1":
            return "modify_tasks"
        elif user_input == "2":
            return "proceed"
        elif user_input == "3":
            return "stop"
        else:
            print("Invalid input. Please enter a valid number.")`

**Comment by DonTido** [comment]
Try adding this to the babyagi.py code. It will prompt you to add feedback, proceed, or exit. Hope this is helpful.

# Add user interactions to the task list

def user_interaction():
    while True:
        print("\033[96m\033[1m" + "\n*****USER INPUT*****\n" + "\033[0m\033[0m")
        print("Select an option:")
        print("1. Modify tasks")
        print("2. Proceed")
        print("3. Stop and exit")
        user_input = input("Enter the number corresponding to your choice: ")

        if user_input == "1":
            return "modify_tasks"
        elif user_input == "2":
            return "proceed"
        elif user_input == "3":
            return "stop"
        else:
            print("Invalid input. Please enter a valid number.")

**Comment by DonTido** [comment]
Add the following code to your babyagi.py file. It will turn the continuous mode off and prompt you at the end of each task to modify the task, proceed, or exit.

`# Add user interactions to the task list
    def user_interaction():
        while True:
            print("\033[96m\033[1m" + "\n*****USER INPUT*****\n" + "\033[0m\033[0m")
            print("Select an option:")
            print("1. Modify tasks")
            print("2. Proceed")
            print("3. Stop and exit")
            user_input = input("Enter the number corresponding to your choice: ")

            if user_input == "1":
                return "modify_tasks"
            elif user_input == "2":
                return "proceed"
            elif user_input == "3":
                return "stop"
            else:
                print("Invalid input. Please enter a valid number.")`

**Comment by jarodchang-sudo** [comment]
where do we put user_interaction() to use in the main code?

**Comment by DonTido** [comment]
Paste it before the #Main Loop section. 
<img width="637" alt="Screenshot 2023-04-19 at 8 21 34 AM" src="https://user-images.githubusercontent.com/130001928/233123145-e0ca256f-aa5f-4374-a9dc-6f998e40ab38.png">

**Comment by DonTido** [comment]
Forgot to add the following section. You will also need to add the following code to the end of the Main Loop.

`# Step 6: User interaction
        user_choice = user_interaction()
        if user_choice == "modify_tasks":
            new_task_name = input("Enter the new task to be added: ")
            new_task = {
                "task_id": tasks_storage.next_task_id(),
                "task_name": new_task_name
            }
            tasks_storage.append(new_task)
            prioritization_agent()
        elif user_choice == "stop":
            break`

**Comment by AllyourBaseBelongToUs** [comment]
Something akin to a "Pause" Button would be appreciated
