### ISSUE TITLE
Issue with running docker compose in windows

### ISSUE THREAD

**Issue by Charul090** [yoheinakajima/babyagi#181]
Hello, getting this error `babyagi-babyagi-1  | /usr/bin/env: ‘python3\r’: No such file or directory
babyagi-babyagi-1 exited with code 127` while running docker-compose up in windows. Have no idea how to solve this. Any help will be appreciated.

**Comment by ultragrin** [comment]
How is this fixed?

**Comment by Ryangr0** [comment]
Could be CLRF stuff. I'd check it.

**Comment by Charul090** [comment]
@Ryangr0 Raised the Pr for fix already. https://github.com/yoheinakajima/babyagi/pull/182

**Comment by francip** [comment]
#182 is merged.
