### ISSUE TITLE
Where are files written?

### ISSUE THREAD

**Issue by Fordari** [yoheinakajima/babyagi#198]
This is a very seemless agent implementation, but I can't seem to sort out where files are stored.

**Comment by francip** [comment]
There are not many files stored right now. The results of the executed tasks are stored currently in Pinecone, and you can use tools/results or tools/results-browser to look at them. That's the only thing currently persisted.

**Comment by kaustubhkfold** [comment]
Same thing here. 7 hours work seamless agent work to create a file but I could not locate the file.

**Comment by cailynyongyong** [comment]
suffered from the same issue, I just created a list that stored all the results and generated an output file by looping through the list 

`
with open('output.txt', 'w') as f:
           for item in result_list:
           f.write(item)
`

**Comment by ericmmartin** [comment]
I ran the script for multiple hours and would like to see the results. When I run `tools/results.py` I get an API token error (`openai.error.AuthenticationError: No API key provided.`). Once I added `openai.api_key = OPENAI_API_KEY` to `main`, it removed the error, but I don't get any results. How can I see the data that was created?
