### ISSUE TITLE
Self-contained bootstrapping with GPT4All and ChromaDB

### ISSUE THREAD

**Issue by TheWaler** [yoheinakajima/babyagi#202]
While having API access to managed services like OpenAI and Pinecone are super valuable, especially for high performance, they require additional set-up steps, complexities, and costs (especially in development).
Adding support for GPT4All models and ChromaDB (which are both Apache 2 Licensed) can help in providing a fully self-contained agent that doesn't _require_ external APIs to function.
If we also include an optional self-bootstrapping that downloads the models locally as well we can have one-click installs that have a fully working, free (both as in beer and as in speech), agent.

Is this something we'd consider interesting or is there a reason this might not be a worthwhile pursuit?
If we like it and there are no obvious blockers I'm happy to take on implementation.

**Comment by francip** [comment]
I just merged two changes - #186 and #218 which add ChromaDB as a default results store and Pinecone as an extension which is automatically triggered for all current Pinecone users.

If you have details on how to enable GPT4All we can easily add it as an extension as well.
