### ISSUE TITLE
bug: too much unnecessary task

### ISSUE THREAD

**Issue by vinliao** [yoheinakajima/babyagi#219]
Simple objective like "take text from japanese.txt, translate with gpt-3.5, write to translated.txt" had 8 tasks, could've been 3. Feels like the "task creator" prompt is forcing the GPT to create tasks even when it's unnecessary.

Taking it to the extreme, this is the result of Babyagi when told to "do nothing":

![image](https://user-images.githubusercontent.com/34117807/233584163-0f519312-f390-4931-91c8-6e04dd871b08.png)

"Watch paint dry for 5 minutes." 😂

This seems to be one of the difference with AutoGPT: in the AutoGPT case, there's the "finish" command if there's no task, but Babyagi needs to finish all tasks before terminating, and not all tasks are aligned with achieving the goal.

**Comment by francip** [comment]
Yes, this is an issue we are working right now.
