### ISSUE TITLE
Inconsistent parsing of task lists

### ISSUE THREAD

**Issue by peteoxenham** [yoheinakajima/babyagi#22]
There is a major issue with how the LLM replies with task lists. The typical response is in the format:
`1. Do something`
but it a few cycles down the chain it commonly becomes
`1: Do something`

I think a better way to parse the task list is needed. Maybe just don't ask the LLM to put numbers there in the first place but still write them out in order? Otherwise, a secondary parsing layer is needed beyond just splitting on delimiters.

**Comment by honeykjoule** [comment]
this is a good, specific example of #16 

need a strat generally to validate inputs from LLMs

**Comment by MicrowaveJak** [comment]
Before validating, this sounds like a problem that can be addressed with prompt engineering. Providing a format or a one-shot prompt of 'a task' should help keep that more consistent

**Comment by mandeeepsingh** [comment]
I think a better way to parse the task list is needed. Maybe just don't ask the LLM to put numbers there in the first place but still write them out in order? Otherwise, a secondary parsing layer is needed beyond just splitting on delimiters.
