### ISSUE TITLE
How to add support for other vector databases?

### ISSUE THREAD

**Issue by hsm207** [yoheinakajima/babyagi#228]
@yoheinakajima  @francip with PR #186 and #218 pinecone is now an extension. It is not clear to me if the this mechanism is generic or specific to pinecone only (neither PRs seem to address this point)

Furthermore,  PR #141 and #111 both had the same goal to add a new vector database but had very distinct approach. Development in these PRs seem to have halted now (but they're still open).

Could you please share some pointers or documentation on what is now the best way to add support for a vector vector database to babyagi?

**Comment by francip** [comment]
it's simple. You only need like twenty steps or so. :-)

1. Copy extensions/pipnecone_store.py and change the logic to use your vector db
2. Copy the code that replaces chroma with pinecone, and make it trigger on an environment variable presence

**Comment by francip** [comment]
Optional:
- write simple docs/myvector.md file with instructions how to setup.

**Comment by francip** [comment]
#141 and #111 are still open because we keep them as examples of implementing numpy, vecto, and weaviate, which I will get to (or someone else can do it) soon and build as extensions using the steps above.

**Comment by hsm207** [comment]
@francip thanks for the pointers. I'll implement weaviate. Could you please assieng #239 to me?
