### ISSUE TITLE
Error using GPT-4

### ISSUE THREAD

**Issue by montenegronyc** [yoheinakajima/babyagi#229]
Switching the model to gpt-4 from gpt-3.5-turbo results in this error:
*** OpenAI API invalid request. Check the documentation for the specific API method you are calling and make sure you are sending valid and complete parameters. Waiting 10 seconds and trying again. ***
No other parameters changed. Anyone know if I need to tweak other settings other than the model in .env (I'm actually running on replit, so using secrets, not an .env file) to get it to work with gpt-4 ?

**Comment by smartin800** [comment]
Also interested in how to resolve this -- running into the same issue

**Comment by micromysore** [comment]
You will need GPT-4 access open openAI to call gpt-4 models 
https://platform.openai.com/docs/models/gpt-4

Please use gpt-3.5-turbo instead.

**Comment by smartin800** [comment]
Thank you micromysore, I missed that before. I signed up for the waitlist. I was also interested in trying model code-davinci-002 but I get a similar invalid message. Any idea on that one (it doesn't seem to be waitlist related)?

**Comment by francip** [comment]
I remember OpenAI tried to shutdown davinci-002, so they might have restricted access to it, don't know. As for GPT-4 - yeah, you need to have API access, which is controlled by OpenAI, and we can't do much about it.

**Comment by francip** [comment]
Closing for now, reopen if you think there's something we can do on BabyAGI side to make this better.

**Comment by johnnyknoxville1337** [comment]
i am using gpt-3.5-turbo and the same error occurs.
