### ISSUE TITLE
Feature: write task execution outputs to separate file.

### ISSUE THREAD

**Issue by jtorreggiani** [yoheinakajima/babyagi#23]
@yoheinakajima, thank you for open-sourcing babyagi! I cloned this repository and had it up and running in no time. I think this project is going to be the spark of a ton of ideas for features, improvements, and future AI projects. I'm exploring how to use this to produce longer-form documents and articles. It would be great to have the ability to selectively output results to a separate file. I wanted to open an issue to introduce myself and get the conversation rolling! I'm going to open a pull request when I get something to work if someone doesn't beat me to the punch!

**Comment by kyleshrader** [comment]
One solution would be to use the following command to write to a file while also displaying in the terminal.

`python3 -u babyagi.py 2>&1 | tee output.txt`
