### ISSUE TITLE
Need a way to organize and collaborate 

### ISSUE THREAD

**Issue by aaronstevenson408** [yoheinakajima/babyagi#238]
Like a wiki for set in stone features and documentation and a discord for continued discussion (i may be suggesting something that already exist)

**Comment by francip** [comment]
We have a Discord, but no Wiki (yet). ping me on Twitter for the link (we are working on fully opening it soon, just still organizing stuff)

**Comment by aaronstevenson408** [comment]
Thank you

**Comment by TunnlMonkey** [comment]
What is the discord channel? @francip
