### ISSUE TITLE
Feature: Automate Copy-Paste Human mode with AutoChatGPT

### ISSUE THREAD

**Issue by 7flash** [yoheinakajima/babyagi#245]
Recently there was a feature added allowing to copy-paste from ChatGPT to avoid spending OpenAI credits.
It can be automated with browser extension, here is a minimal example I made, where two instances of ChatGPT communicate, but we can make replace second instance in example with babyagi. https://github.com/7flash/AutoChatGPT

**Comment by francip** [comment]
I'd love this. There's two approaches:
1. You take your extension code and put in a subfolder in tools with a simple README how to install and run it. :-)
2. Or if you prefer to keep it in your own repo, we can add a simple print() ni the main script that point folks in Human mode to your extension as a helper to improve their experience.
