### ISSUE TITLE
Where do I find the output from the tasks?

### ISSUE THREAD

**Issue by mjdyibrahim** [yoheinakajima/babyagi#291]
I'm able to see the tasks on the terminal, but once my instance is closed all the tasks and outcomes are gone. How can I retrieve the output from previous sessions?

I sat the following .env variable 
COOPERATIVE_MODE=local

**Comment by yesbroc** [comment]
i dont think you can, you can try ContextFound's fork or just use `python babyagi.py > output.txt` - that saves the output to a txt file, side effect is that you can only see its thoughts after running.

**Comment by robertgro** [comment]
Did you installed the [required libraries](https://github.com/yoheinakajima/babyagi/blob/main/extensions/requirements.txt) before? (especially ray)

As you can see, the implementation is [still there](https://github.com/search?q=repo%3Ayoheinakajima/babyagi%20COOPERATIVE_MODE&type=code), but I couldn't test it myself yet.

Maybe this is what you looking for: [how do you stop it and retrieve info later? #53](https://github.com/yoheinakajima/babyagi/issues/53#issuecomment-1535090795)

According to [VirusTotal](https://www.virustotal.com/gui/url/1b96c1e062c210b4762e55f697180c6e04ae7fd433759d669731a255cab2c415), the file referenced should be safe, providing python code to implement a log to a file mechanism.
