### ISSUE TITLE
.env file not updating openai api key

### ISSUE THREAD

**Issue by commonbeing** [yoheinakajima/babyagi#296]
I revoked my API key on the openai site and created a new key.

 I then changed the API key in the .env file to the new key.

Now when running it errors out on the API key being wrong and I can see it's still referencing the old key.

I find this strange as the .env file updates the task no problem.

So where it storing the openAI API key? if it is not referencing the .env file for the API key when executing babyAGI.py the it must be passing the key to somewhere else when first run, which makes the whole purpose of an .env for securing API keys pointless.

**Comment by r3cha** [comment]
if you not stopped container yet use `docker compose up -d`
