### ISSUE TITLE
Why is OPENAI_API_KEY still necessary?

### ISSUE THREAD

**Issue by razvanab** [yoheinakajima/babyagi#297]
Why is OPENAI_API_KEY still necessary if we can use an alternative model like llama?

**Comment by Nai-mul** [comment]
I have similar question like you, Open AI subscriptions are not intended for scientific research.  It charges a lot of fees.

**Comment by yesbroc** [comment]
openai is normally faster and better

**Comment by shiloh92** [comment]
Yeah open source and free is needed to open up this area for everyone.

**Comment by yesbroc** [comment]
not saying i was against it, just that openai has better models for use, gpt 3.5 is good, fast, and cheap

**Comment by francip** [comment]
OpenAI key is needed for people that use OpenAI models. It's quite possible there is assertion that checks if the env variable is there even if people are using Llama.cpp, I'll look into fixing this. But it only checks if the variable is there, doesn't use it for anything in that case, so workaround is to set it to some dummy value.

**Comment by razvanab** [comment]
openai.error.AuthenticationError: Incorrect API key provided: v6j0grklw3. You can find your API key at https://platform.openai.com/account/api-keys.
