### ISSUE TITLE
Suggestion: change llama-cpp-python==0.1.36 to llama-cpp-python>=0.1.36

### ISSUE THREAD

**Issue by vmajor** [yoheinakajima/babyagi#300]
llama.cpp and ggml quantization changes so quickly that your requirement is verry far behind the current version and models, specifically the new 5q and 5_1q models.

I manually updated to the latest version and it appears to work fine.

**Comment by matthoffner** [comment]
https://github.com/yoheinakajima/babyagi/pull/299

**Comment by jonathansheets517** [comment]
thanks @vmajor

**Comment by matthoffner** [comment]
Updated #299 to `>=` so  it picks up latest by default

**Comment by francip** [comment]
Merged
