### ISSUE TITLE
Two confusions about autonomous agents

### ISSUE THREAD

**Issue by RudyGuo** [yoheinakajima/babyagi#304]
How to let the agent optimize decisions based on feedbacks
How can I transfer my knowledge and experience to the LLM? Let the agent refer to my documents to make decisions.

**Comment by jsemrau** [comment]
To my knowledge there are only a few options where babyagi runs with a human feedback loop.
https://twitter.com/FelipeSchieber/status/1657932571798380547
and
https://www.scriptkit.com/mabry1985/an-example-of-an-agi-task-manager-with-human-in-the-loop-feedback

If you look at this image:
https://pbs.twimg.com/media/FwIpHnyWYAEpgA2?format=png&name=medium
You can see what would be necessary to add human interaction into the loop.
