### ISSUE TITLE
Rate Limit Error

### ISSUE THREAD

**Issue by shubham184** [yoheinakajima/babyagi#32]
Getting error: `openai.error.RateLimitError: You exceeded your current quota, please check your plan and billing details` at
`return openai.Embedding.create(input=[text], model="text-embedding-ada-002")["data"][0]["embedding"]`

![image](https://user-images.githubusercontent.com/38903550/229775963-b6f4447f-6a1b-4a42-9bfa-d98257bb3c6f.png)

**Comment by honeykjoule** [comment]
you maxxed out the $120 quota? or too many requests too quickly?

**Comment by DrewMcArthur** [comment]
you sure that the api key you're using is the one you're looking at on the open ai billing page?  i don't think this is something that can be fixed in the code here.

**Comment by gulatisukaran** [comment]
yeah, this issue is probably related to your account.

**Comment by siddiqss** [comment]
Are you on free trial? I had similar issue and my free trial was expired. Added my card and created a new API key. This resolved my issue

**Comment by lupuleasa-core** [comment]
auto-gpt project has a similar problem
https://github.com/Torantulino/Auto-GPT/issues/79

it is likely free accounts dont work anymore (disabled from openai end)

**Comment by Korben00** [comment]
I suggested a correction [here](https://github.com/yoheinakajima/babyagi/pull/63).
