### ISSUE TITLE
Illegal instruction (core dumped)

### ISSUE THREAD

**Issue by dirkjbreeuwer** [yoheinakajima/babyagi#326]
Hi team, 

I am trying to run babyagi in an Ubuntu VM. I've installed requirements in a python virtual environment and added my open ai keys to the .env. 

When I run python3 babyagi.py I get:

Illegal instruction (core dumped)

I did some research online and all I could find was talk about the TensorFlow library, but this project isn't using this library. 

Any help would be appreciated. 

Note, it must be something related to my VM as it works fine using one of the GitHub codespaces.

**Comment by dropitlikecross** [comment]
This issue typically occurs in the following situations:

    You are using an incompatible version of Tensor with what the project requires.
    Your Python permissions are misconfigured.
    If you are utilizing a local language model, it may be an unsupported version.

**Comment by 13331112522** [comment]
I met the same problem in my ubuntu docker. It seems that chroma vecterdb has conflict with env, try to switch to FAISS. And loading the local llama-cpp model in my case also met the problem, maybe could try another.
