### ISSUE TITLE
AssertionError: OPENAI_API_KEY environment variable is missing from .env

### ISSUE THREAD

**Issue by pankyye** [yoheinakajima/babyagi#340]
Hi 

every time I run python3 babyagi.py, there display an error:

Using embedded DuckDB without persistence: data will be transient
Traceback (most recent call last):
  File "/Users/panky/babyagi/babyagi.py", line 33, in <module>
    assert OPENAI_API_KEY, "\033[91m\033[1m" + "OPENAI_API_KEY environment variable is missing from .env" + "\033[0m\033[0m"
AssertionError: OPENAI_API_KEY environment variable is missing from .env

I have setup the openai API key in the  .eve file, does any one could help me figure out what is going on here? Thanks!

**Comment by Meghansh-Maurya** [comment]
Try to make a new ".env" file and again do the same. I think you are using Example file(.env.example)
