### ISSUE TITLE
Support to set openapi api URL to run with LocalAI

### ISSUE THREAD

**Issue by skywalker123p** [yoheinakajima/babyagi#381]
Please Support to set openapi api URL to run with LocalAI. Thanks.

**Comment by maxlemieux** [comment]
I tried adding it just after where the key is set, but it didn't work (still tries to contact the OpenAI URL):

```
# Configure OpenAI
openai.api_key = OPENAI_API_KEY

# Configure OpenAI base URL
OPENAI_BASE_URL = os.getenv("OPENAI_BASE_URL", "")
openai.base_url = OPENAI_BASE_URL
```

**Comment by little51** [comment]
You can take a look at https://github.com/git-cloner/babyagi ,I add an OPENAI_API_BASE parameter in .env file
