### ISSUE TITLE
Project still active?

### ISSUE THREAD

**Issue by ehausen** [yoheinakajima/babyagi#384]
Is this project still active? There is quite a long list of open Pull request and Issues.

@yoheinakajima, any insight on this?

If this is not active anymore, which fork would be the most active one?

**Comment by yoheinakajima** [comment]
No it's not... I had some volunteer helpers in the early days - but I personally don't have capacity to maintain repos. I mostly release these as ideas to share and for others to build upon.

Started working on a new version from scratch but might make it a different repo. I'll ask around to see if there's a better supported version of BabyAGI.
