### ISSUE TITLE
Overshooting by the task creation agent

### ISSUE THREAD

**Issue by giorgiop** [yoheinakajima/babyagi#45]
I am of the opinion that the `task_creation_agent` should understand when a task should *not* be split up in a long list of tasks.

Here's an example of a particular failure.

Counter-argument: obviously this task can be performed well by GPT-4 alone, so I may overthink the issue. But
- we want babyagi to fall back to a single (or few) call to GPT-4 when the problem is easy enough
- the `task_creation_agent` should know when 2 vs 5 or 10 are enough

```
*****OBJECTIVE*****

Write a list of the top 5 countries for best food in the world

*****TASK LIST*****

1: Develop a task list

*****NEXT TASK*****

1: Develop a task list

*****TASK RESULT*****

1. Research food cultures around the world 
2. Evaluate the quality of food in each country 
3. Research popular dishes in each country 
4. Rank countries based on the quality and variety of their cuisine 
5. Create a list of the top 5 countries for best food in the world
You are a task creation AI that uses the result of an execution agent to create new tasks with the following objective: Write a list of the top 5 countries for best food in the world, The last completed task has the result: {'data': '1. Research food cultures around the world \n2. Evaluate the quality of food in each country \n3. Research popular dishes in each country \n4. Rank countries based on the quality and variety of their cuisine \n5. Create a list of the top 5 countries for best food in the world'}. This result was based on this task description: Develop a task list. These are incomplete tasks: . Based on the result, create new tasks to be completed by the AI system that do not overlap with incomplete tasks. Return the tasks as an array.

*****TASK LIST*****

2: Analyze the quality of the ingredients used in each country's cuisine
3: Gather information on the ingredients used in each country's cuisine
4: Compare the cooking methods used in each country's cuisine
5: Assess the presentation of food in each country
6: Compare the cost of food in each country
7: Write a list of the top 5 countries for best food in the world

*****NEXT TASK*****

2: Analyze the quality of the ingredients used in each country's cuisine

*****TASK RESULT*****

1. France - French cuisine is renowned for its high-quality ingredients, such as butter, cream, and fresh produce.
2. Italy - Italian cuisine is renowned for using fresh, seasonal ingredients, such as tomatoes, olives, and artichokes.
3. Japan - Japanese cuisine is renowned for its use of fresh seafood, such as tuna, eel, and squid.
4. China - Chinese cuisine is renowned for its use of fresh vegetables, such as cabbage, bok choy, and mushrooms.
5. India - Indian cuisine is renowned for its use of spices, such as cumin, turmeric, and coriander.
You are a task creation AI that uses the result of an execution agent to create new tasks with the following objective: Write a list of the top 5 countries for best food in the world, The last completed task has the result: {'data': '1. France - French cuisine is renowned for its high-quality ingredients, such as butter, cream, and fresh produce.\n2. Italy - Italian cuisine is renowned for using fresh, seasonal ingredients, such as tomatoes, olives, and artichokes.\n3. Japan - Japanese cuisine is renowned for its use of fresh seafood, such as tuna, eel, and squid.\n4. China - Chinese cuisine is renowned for its use of fresh vegetables, such as cabbage, bok choy, and mushrooms.\n5. India - Indian cuisine is renowned for its use of spices, such as cumin, turmeric, and coriander.'}. This result was based on this task description: Analyze the quality of the ingredients used in each country's cuisine. These are incomplete tasks: Gather information on the ingredients used in each country's cuisine, Compare the cooking methods used in each country's cuisine, Assess the presentation of food in each country, Compare the cost of food in each country, Write a list of the top 5 countries for best food in the world. Based on the result, create new tasks to be completed by the AI system that do not overlap with incomplete tasks. Return the tasks as an array.

*****TASK LIST*****

3: Assess the presentation of food in each country
4: Compare the cost of food in each country
5: Research the regional variations of each country's cuisine
6: Analyze the cultural influences on each country's cuisine
7: Compare the nutritional value of food from each country
8: Investigate the history of each country's cuisine
9: Evaluate the sustainability of food production in each country
10: Write a list of the top 5 countries for best food

*****NEXT TASK*****

3: Assess the presentation of food in each country

*****TASK RESULT*****

1. France - French cuisine is known for its exquisite presentation, with dishes often composed like works of art.
2. Japan - Japanese food is often presented in an aesthetically-pleasing way, with beautiful plating and intricate designs.
3. Italy - Italian cuisine is renowned for its eye-catching presentation, with dishes often decorated with edible garnishes.
4. Thailand - Thailand's elegant food presentation includes vibrant colors and intricate details, making it a feast for the eyes as well as the taste buds.
5. India - Indian food is known for its beautiful presentation, with dishes often garnished with edible flowers and herbs.
You are a task creation AI that uses the result of an execution agent to create new tasks with the following objective: Write a list of the top 5 countries for best food in the world, The last completed task has the result: {'data': "1. France - French cuisine is known for its exquisite presentation, with dishes often composed like works of art.\n2. Japan - Japanese food is often presented in an aesthetically-pleasing way, with beautiful plating and intricate designs.\n3. Italy - Italian cuisine is renowned for its eye-catching presentation, with dishes often decorated with edible garnishes.\n4. Thailand - Thailand's elegant food presentation includes vibrant colors and intricate details, making it a feast for the eyes as well as the taste buds.\n5. India - Indian food is known for its beautiful presentation, with dishes often garnished with edible flowers and herbs."}. This result was based on this task description: Assess the presentation of food in each country. These are incomplete tasks: Compare the cost of food in each country, Research the regional variations of each country's cuisine, Analyze the cultural influences on each country's cuisine, Compare the nutritional value of food from each country, Investigate the history of each country's cuisine, Evaluate the sustainability of food production in each country, Write a list of the top 5 countries for best food. Based on the result, create new tasks to be completed by the AI system that do not overlap with incomplete tasks. Return the tasks as an array.
```

**Comment by Gogolian** [comment]
So basically the question is:
How should we assess, when something is a task to be split intio smaller tasks, and when something should be an answer that would be left alone.

**Comment by Abduljakulsalsal** [comment]
> I am of the opinion that the `task_creation_agent` should understand when a task should _not_ be split up in a long list of tasks.
> 
> Here's an example of a particular failure.
> 
> Counter-argument: obviously this task can be performed well by GPT-4 alone, so I may overthink the issue. But
> 
> * we want babyagi to fall back to a single (or few) call to GPT-4 when the problem is easy enough
> * the `task_creation_agent` should know when 2 vs 5 or 10 are enough
> 
> ```
> *****OBJECTIVE*****
> 
> Write a list of the top 5 countries for best food in the world
> 
> *****TASK LIST*****
> 
> 1: Develop a task list
> 
> *****NEXT TASK*****
> 
> 1: Develop a task list
> 
> *****TASK RESULT*****
> 
> 1. Research food cultures around the world 
> 2. Evaluate the quality of food in each country 
> 3. Research popular dishes in each country 
> 4. Rank countries based on the quality and variety of their cuisine 
> 5. Create a list of the top 5 countries for best food in the world
> You are a task creation AI that uses the result of an execution agent to create new tasks with the following objective: Write a list of the top 5 countries for best food in the world, The last completed task has the result: {'data': '1. Research food cultures around the world \n2. Evaluate the quality of food in each country \n3. Research popular dishes in each country \n4. Rank countries based on the quality and variety of their cuisine \n5. Create a list of the top 5 countries for best food in the world'}. This result was based on this task description: Develop a task list. These are incomplete tasks: . Based on the result, create new tasks to be completed by the AI system that do not overlap with incomplete tasks. Return the tasks as an array.
> 
> *****TASK LIST*****
> 
> 2: Analyze the quality of the ingredients used in each country's cuisine
> 3: Gather information on the ingredients used in each country's cuisine
> 4: Compare the cooking methods used in each country's cuisine
> 5: Assess the presentation of food in each country
> 6: Compare the cost of food in each country
> 7: Write a list of the top 5 countries for best food in the world
> 
> *****NEXT TASK*****
> 
> 2: Analyze the quality of the ingredients used in each country's cuisine
> 
> *****TASK RESULT*****
> 
> 1. France - French cuisine is renowned for its high-quality ingredients, such as butter, cream, and fresh produce.
> 2. Italy - Italian cuisine is renowned for using fresh, seasonal ingredients, such as tomatoes, olives, and artichokes.
> 3. Japan - Japanese cuisine is renowned for its use of fresh seafood, such as tuna, eel, and squid.
> 4. China - Chinese cuisine is renowned for its use of fresh vegetables, such as cabbage, bok choy, and mushrooms.
> 5. India - Indian cuisine is renowned for its use of spices, such as cumin, turmeric, and coriander.
> You are a task creation AI that uses the result of an execution agent to create new tasks with the following objective: Write a list of the top 5 countries for best food in the world, The last completed task has the result: {'data': '1. France - French cuisine is renowned for its high-quality ingredients, such as butter, cream, and fresh produce.\n2. Italy - Italian cuisine is renowned for using fresh, seasonal ingredients, such as tomatoes, olives, and artichokes.\n3. Japan - Japanese cuisine is renowned for its use of fresh seafood, such as tuna, eel, and squid.\n4. China - Chinese cuisine is renowned for its use of fresh vegetables, such as cabbage, bok choy, and mushrooms.\n5. India - Indian cuisine is renowned for its use of spices, such as cumin, turmeric, and coriander.'}. This result was based on this task description: Analyze the quality of the ingredients used in each country's cuisine. These are incomplete tasks: Gather information on the ingredients used in each country's cuisine, Compare the cooking methods used in each country's cuisine, Assess the presentation of food in each country, Compare the cost of food in each country, Write a list of the top 5 countries for best food in the world. Based on the result, create new tasks to be completed by the AI system that do not overlap with incomplete tasks. Return the tasks as an array.
> 
> *****TASK LIST*****
> 
> 3: Assess the presentation of food in each country
> 4: Compare the cost of food in each country
> 5: Research the regional variations of each country's cuisine
> 6: Analyze the cultural influences on each country's cuisine
> 7: Compare the nutritional value of food from each country
> 8: Investigate the history of each country's cuisine
> 9: Evaluate the sustainability of food production in each country
> 10: Write a list of the top 5 countries for best food
> 
> *****NEXT TASK*****
> 
> 3: Assess the presentation of food in each country
> 
> *****TASK RESULT*****
> 
> 1. France - French cuisine is known for its exquisite presentation, with dishes often composed like works of art.
> 2. Japan - Japanese food is often presented in an aesthetically-pleasing way, with beautiful plating and intricate designs.
> 3. Italy - Italian cuisine is renowned for its eye-catching presentation, with dishes often decorated with edible garnishes.
> 4. Thailand - Thailand's elegant food presentation includes vibrant colors and intricate details, making it a feast for the eyes as well as the taste buds.
> 5. India - Indian food is known for its beautiful presentation, with dishes often garnished with edible flowers and herbs.
> You are a task creation AI that uses the result of an execution agent to create new tasks with the following objective: Write a list of the top 5 countries for best food in the world, The last completed task has the result: {'data': "1. France - French cuisine is known for its exquisite presentation, with dishes often composed like works of art.\n2. Japan - Japanese food is often presented in an aesthetically-pleasing way, with beautiful plating and intricate designs.\n3. Italy - Italian cuisine is renowned for its eye-catching presentation, with dishes often decorated with edible garnishes.\n4. Thailand - Thailand's elegant food presentation includes vibrant colors and intricate details, making it a feast for the eyes as well as the taste buds.\n5. India - Indian food is known for its beautiful presentation, with dishes often garnished with edible flowers and herbs."}. This result was based on this task description: Assess the presentation of food in each country. These are incomplete tasks: Compare the cost of food in each country, Research the regional variations of each country's cuisine, Analyze the cultural influences on each country's cuisine, Compare the nutritional value of food from each country, Investigate the history of each country's cuisine, Evaluate the sustainability of food production in each country, Write a list of the top 5 countries for best food. Based on the result, create new tasks to be completed by the AI system that do not overlap with incomplete tasks. Return the tasks as an array.
> ```

**Comment by giorgiop** [comment]
> So basically the question is: How should we assess, when something is a task to be split intio smaller tasks, and when something should be an answer that would be left alone.

yes I think so
