### ISSUE TITLE
Add Local LLMs - Enhancement

### ISSUE THREAD

**Issue by Meathelix1** [yoheinakajima/babyagi#48]
Would like to see local LLMS like Alpaca and Llama.

**Comment by francip** [comment]
Yeah, I am working on this (among the countless other things I want to do with babyAGI :-)). Hopefully end of this week.

**Comment by drusepth** [comment]
I have babyagi working with Llama/Alpaca [in this commit](https://github.com/drusepth/babyagi/blob/54e80f95059ab52a8151c3d936ab2c9eb7dae059/babyagi-alpaca.py). The code is messy but works; might be helpful for anyone else that wants to clean it up and properly implement it.

**Comment by jakvb** [comment]
#208 here it is implemented and working with vicuna
