### ISSUE TITLE
Library of tasks and outputs

### ISSUE THREAD

**Issue by trilloc** [yoheinakajima/babyagi#66]
Hi Gentlefolks,

After the task list crashed again because of OpenAi being overloaded with requests, I thought it might be a good idea if you could create a task and output library that can be reused from the cloud. 

Cheers

**Comment by koltregaskes** [comment]
Having the terminal text outputted to a text file would be great.  I noticed that it was repeating tasks and seem to get stuck in a loop so I ended the task.  If there was some output then I could review what might have happened.
