### ISSUE TITLE
Error when running the script

### ISSUE THREAD

**Issue by cyprints** [yoheinakajima/babyagi#77]
Import "openai" could not be resolved
Import "openai" could not be resolved
Import "openai" could not be resolved

**Comment by kyleshrader** [comment]
In the readme there is a remark about how to setup the project. You will need to pip install -r requirements.txt

**Comment by micromysore** [comment]
Its due to open 0.27.2 no longer resolving, I have pushed a PR to use 0.27.4, which should fix this issue.

**Comment by francip** [comment]
You can also do manually pip install openai.
@micromysore fix is also merged, so pulling from upstream should also help.
