### ISSUE TITLE
The task list becomes hyper-focused over time.

### ISSUE THREAD

**Issue by kyleshrader** [yoheinakajima/babyagi#78]
Over time the list of tasks be comes more and more similar.
This is likely due to the task list using during the creation of tasks, creating a bias in the format and topics used in the newly created tasks.
It's also possible that this is exaggerated by the task list being being cut off at certain lengths when the max_token limit is hit and more tasks aren't generated, especially when tasks become longer in description.

These screenshots have about 3 iterations between each, but notice the second has an item cutoff due to the length, resulting in a loss of that item by the reprioritization the next iteration.

![image](https://user-images.githubusercontent.com/5632571/230683697-d2cd6fae-4696-442f-9755-01c727a6f59e.png)

![image](https://user-images.githubusercontent.com/5632571/230684194-9092f697-0662-4939-be32-1baaa5b4fd4f.png)

![image](https://user-images.githubusercontent.com/5632571/230684051-21323893-c0a0-4a03-a546-be95d587c977.png)

**Comment by micromysore** [comment]
Have you tried to change / edit the prompts within each of the agent functions to explore what if would work. This would be prompt engineering.

**Comment by francip** [comment]
Brillaugte (on Discord) is already working on some improvements.

**Comment by kyleshrader** [comment]
> Have you tried to change / edit the prompts within each of the agent functions to explore what if would work. This would be prompt engineering.

A little bit, but with no success. I didn't spend too long modifying it though, because I was working on a code change that I didn't want to deviate much from the original. I will try to spend more time manipulating the prompt to overcome some of the issues I experienced when I get a chance. (also keeping my eyes on that discussion in discord)

**Comment by transcendr** [comment]
In its current state, it seems there can be no end/completion state.  It often gets caught in a loop and/or repeats tasks with slightly different wording.  Ideally the agent should reflect on whether the current list of tasks are sufficient enough to complete the objective and only if the answer is no, generate and prioritize a new list of tasks.  I have personally never been able to get it to complete a task, meaning get to the last task in the list, finish it.  Also the code in its current state doesn't seem to have any shut down condition, unless I missed it.

**Comment by abhiprojectz** [comment]
Any thoughts on integrating with this ? 

[https://github.com/abhiprojectz/SingularGPT](https://github.com/abhiprojectz/SingularGPT)
