### ISSUE TITLE
Problem with Pinecone

### ISSUE THREAD

**Issue by Onesens** [yoheinakajima/babyagi#81]
What should be written in the following, I'm having error messages about pinecone & table name. Can you give an example? 
Is the table name an index in pincone? I'm a noob coder, actually I don't know sh*t about coding so help would be helpful :D/

PINECONE_ENVIRONMENT=

# TABLE CONFIG
TABLE_NAME=

**Comment by kyleshrader** [comment]
The table_name is the index that is created in pinecone.
The environment will be the region on pinecone servers, such as `us-east1-gcp`.

**Comment by micromysore** [comment]
@Onesens if you visit https://app.pinecone.io/, check API keys on left hand side. 

you will see Environment
For table name, you can use anything

**Comment by francip** [comment]
![image](https://user-images.githubusercontent.com/49422/230713769-37b34ece-d3b9-4de4-b574-97e5054afdc8.png)

Environment is us-west4-gcp for me. Index is the table name where BabyAGI will store the results.

If you have not created the table yet, BabyAGI will create it for you, so just pick a name you like. test-table is fine :-)
You can find the environment also in the Organizations/Project tab.
