### ISSUE TITLE
Anyone know a way to handle disconnection from OpenAI issues?

### ISSUE THREAD

**Issue by cklose2000** [yoheinakajima/babyagi#89]
Just got this error:
ConnectionResetError: [Errno 104] Connection reset by peer

Anyone have thoughts about building in some kind of retry method to enable Babyagi to keep running if OpenAI hangs up for awhile?

**Comment by clickbrain** [comment]
I saw another issue about this. I had the same thing just happen. What I would like to know if there is anyway to restart from where it crashed.
